name: build

on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
  push:
    paths-ignore:
      - 'Documentation/**'
    branches:
      - master
      - 'releases/*'
    tags:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake make gcc -y
      - name: build project
        run: |
          cmake -H. -Bbuild
          cmake --build build -j
